spring:
  application:
    name: 郎家岭伯爵
  redis:
    ssl: false
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    password:
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20

server:
  tomcat:
    relaxed-path-chars:
      - '{'
      - '}'
      - '['
      - ']'
    relaxed-query-chars:
      - '{'
      - '}'
      - '['
      - ']'