spring:
  application:
    name: 郎家岭伯爵
  redis:
    ssl: false
    host: redis-18896.c251.east-us-mz.azure.cloud.redislabs.com
    port: 18896
    database: 0
    timeout: 1000
    password: 6ZQUfEmkUDtiVENJQY9RaXK2XzpyrPEG
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        min-idle: 0
        max-idle: 20

server:
  tomcat:
    relaxed-path-chars:
      - '{'
      - '}'
      - '['
      - ']'
    relaxed-query-chars:
      - '{'
      - '}'
      - '['
      - ']'